### ISSUE TITLE
Obsolete location handling

### ISSUE THREAD

**Issue by dimonik** [vyshane/rex-weather#11]
Usage of LocationManager/LocationService is not recommended by Google, it is better to use com.google.android.gms.location.LocationServices from GMS library.

**Comment by vyshane** [comment]
As far as I know, [LocationManager](http://developer.android.com/reference/android/location/LocationManager.html) has not been deprecated. There are valid reasons to use it, e.g. if you don't want a dependency on Google Play Services.

I don't really care either way for this demo project. However, I don't really have the motivation to switch APIs since it's just a demo project.
